package com.github.stefvanschie.quickskript.core.psi.condition;

import com.github.stefvanschie.quickskript.core.skript.SkriptLoader;
import com.github.stefvanschie.quickskript.core.skript.StandaloneSkriptLoader;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;

import static org.junit.jupiter.api.Assertions.assertInstanceOf;

class PsiIsHandRaisedConditionTest {

    private static SkriptLoader loader;

    @BeforeAll
    static void init() {
        loader = new StandaloneSkriptLoader();
    }

    @ParameterizedTest
    @ValueSource(strings = {
        "player's main hands is raised",
        "player's main hands are raised",
        "player's main hand is raised",
        "player's main hand are raised",
        "player's hands is raised",
        "player's hands are raised",
        "player's hand is raised",
        "player's hand are raised",
        "player' main hands is raised",
        "player' main hands are raised",
        "player' main hand is raised",
        "player' main hand are raised",
        "player' hands is raised",
        "player' hands are raised",
        "player' hand is raised",
        "player' hand are raised",
        "main hands of player is raised",
        "main hands of player are raised",
        "main hand of player is raised",
        "main hand of player are raised",
        "hands of player is raised",
        "hands of player are raised",
        "hand of player is raised",
        "hand of player are raised",
        "player's main hands isn't raised",
        "player's main hands is not raised",
        "player's main hands aren't raised",
        "player's main hands are not raised",
        "player's main hand isn't raised",
        "player's main hand is not raised",
        "player's main hand aren't raised",
        "player's main hand are not raised",
        "player's hands isn't raised",
        "player's hands is not raised",
        "player's hands aren't raised",
        "player's hands are not raised",
        "player's hand isn't raised",
        "player's hand is not raised",
        "player's hand aren't raised",
        "player's hand are not raised",
        "player' main hands isn't raised",
        "player' main hands is not raised",
        "player' main hands aren't raised",
        "player' main hands are not raised",
        "player' main hand isn't raised",
        "player' main hand is not raised",
        "player' main hand aren't raised",
        "player' main hand are not raised",
        "player' hands isn't raised",
        "player' hands is not raised",
        "player' hands aren't raised",
        "player' hands are not raised",
        "player' hand isn't raised",
        "player' hand is not raised",
        "player' hand aren't raised",
        "player' hand are not raised",
        "main hands of player isn't raised",
        "main hands of player is not raised",
        "main hands of player aren't raised",
        "main hands of player are not raised",
        "main hand of player isn't raised",
        "main hand of player is not raised",
        "main hand of player aren't raised",
        "main hand of player are not raised",
        "hands of player isn't raised",
        "hands of player is not raised",
        "hands of player aren't raised",
        "hands of player are not raised",
        "hand of player isn't raised",
        "hand of player is not raised",
        "hand of player aren't raised",
        "hand of player are not raised",
        "player's off hands is raised",
        "player's off hands are raised",
        "player's off hand is raised",
        "player's off hand are raised",
        "player's off-hands is raised",
        "player's off-hands are raised",
        "player's off-hand is raised",
        "player's off-hand are raised",
        "player's offhands is raised",
        "player's offhands are raised",
        "player's offhand is raised",
        "player's offhand are raised",
        "player' off hands is raised",
        "player' off hands are raised",
        "player' off hand is raised",
        "player' off hand are raised",
        "player' off-hands is raised",
        "player' off-hands are raised",
        "player' off-hand is raised",
        "player' off-hand are raised",
        "player' offhands is raised",
        "player' offhands are raised",
        "player' offhand is raised",
        "player' offhand are raised",
        "off hands of player is raised",
        "off hands of player are raised",
        "off hand of player is raised",
        "off hand of player are raised",
        "off-hands of player is raised",
        "off-hands of player are raised",
        "off-hand of player is raised",
        "off-hand of player are raised",
        "offhands of player is raised",
        "offhands of player are raised",
        "offhand of player is raised",
        "offhand of player are raised",
        "player's off hands isn't raised",
        "player's off hands is not raised",
        "player's off hands aren't raised",
        "player's off hands are not raised",
        "player's off hand isn't raised",
        "player's off hand is not raised",
        "player's off hand aren't raised",
        "player's off hand are not raised",
        "player's off-hands isn't raised",
        "player's off-hands is not raised",
        "player's off-hands aren't raised",
        "player's off-hands are not raised",
        "player's off-hand isn't raised",
        "player's off-hand is not raised",
        "player's off-hand aren't raised",
        "player's off-hand are not raised",
        "player's offhands isn't raised",
        "player's offhands is not raised",
        "player's offhands aren't raised",
        "player's offhands are not raised",
        "player's offhand isn't raised",
        "player's offhand is not raised",
        "player's offhand aren't raised",
        "player's offhand are not raised",
        "player' off hands isn't raised",
        "player' off hands is not raised",
        "player' off hands aren't raised",
        "player' off hands are not raised",
        "player' off hand isn't raised",
        "player' off hand is not raised",
        "player' off hand aren't raised",
        "player' off hand are not raised",
        "player' off-hands isn't raised",
        "player' off-hands is not raised",
        "player' off-hands aren't raised",
        "player' off-hands are not raised",
        "player' off-hand isn't raised",
        "player' off-hand is not raised",
        "player' off-hand aren't raised",
        "player' off-hand are not raised",
        "player' offhands isn't raised",
        "player' offhands is not raised",
        "player' offhands aren't raised",
        "player' offhands are not raised",
        "player' offhand isn't raised",
        "player' offhand is not raised",
        "player' offhand aren't raised",
        "player' offhand are not raised",
        "off hands of player isn't raised",
        "off hands of player is not raised",
        "off hands of player aren't raised",
        "off hands of player are not raised",
        "off hand of player isn't raised",
        "off hand of player is not raised",
        "off hand of player aren't raised",
        "off hand of player are not raised",
        "off-hands of player isn't raised",
        "off-hands of player is not raised",
        "off-hands of player aren't raised",
        "off-hands of player are not raised",
        "off-hand of player isn't raised",
        "off-hand of player is not raised",
        "off-hand of player aren't raised",
        "off-hand of player are not raised",
        "offhands of player isn't raised",
        "offhands of player is not raised",
        "offhands of player aren't raised",
        "offhands of player are not raised",
        "offhand of player isn't raised",
        "offhand of player is not raised",
        "offhand of player aren't raised",
        "offhand of player are not raised"
    })
    void test(String input) {
        assertInstanceOf(PsiIsHandRaisedCondition.class, loader.tryParseElement(input, -1));
    }
}
